version=${version-1.0}
status Setting up the Connect module $version
[ -n "$modlib" ] && mkdir -p "$modlib/connect-client" 2>/dev/null
[ -n "$modlib" ] && dst="$modlib/connect-client" || dst="$base"

modules=$(
	module -t list 2>&1 | grep -v Currently | while read module; do
		printf "module load $module~"
	done
)

sed <connect.in \
	-e "s!@CONNECTDIR@!$base!g" \
	-e "s!@MODULES@!$modules!g" \
	| tr '~' '\012' >"$dst/$version"

echo "Connect modulefile is in $dst/connect-client"
