status Setting up the switch-module scripts
sed -e "s!BASE!$base!g" -i '' setup-switch-command.csh
mkdir ${base}/switch
cp switch-modules.sh ${base}/switch
cp switch-modules.ksh ${base}/switch
cp switch-modules.csh ${base}/switch
cp setup-switch-command.csh ${base}/switch
ln -s ${base}/switch/setup-switch-command.csh /etc/profile.d/zzz-ci-connect.csh
ln -s ${base}/switch/switch-modules.sh /etc/profile.d/zzz-ci-connect.sh
