status Setting up the switch-module scripts
sed -i -e "s|BASE|$base|" setup-switch-command.csh
if [ ! -e ${base}/switch ];
then
  mkdir ${base}/switch
fi
cp switch-modules.sh ${base}/switch
cp switch-modules.ksh ${base}/switch
cp switch-modules.csh ${base}/switch
cp setup-switch-command.csh ${base}/switch
ln -s ${base}/switch/setup-switch-command.csh /etc/profile.d/zzz-ci-connect.csh
ln -s ${base}/switch/switch-modules.sh /etc/profile.d/zzz-ci-connect.sh
